name: Notificación por correo a Gmail

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar correo a Gmail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  
          server_port: 25  
          username: actionsgithubpractica2@gmail.com
          password: ActionsPractica2
          subject: "Notificación de Push en la rama ${{ github.ref_name }}"
          body: |
            Se ha realizado un push en la rama **${{ github.ref_name }}**.

            - **Autor**: ${{ github.actor }}
            - **Mensaje del commit**: ${{ github.event.head_commit.message }}
            - **Ver commit**: [Ver commit](${{ github.event.head_commit.url }})

          to: actionsgithubpractica2@gmail.com
          from: actionsgithubpractica2@gmail.com